---
title: "REU-Curriculum"
author: "Yohn Jairo Parra Bautista, PhD. and Carlos Theran, PhD."
date: "5/14/2021"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Hands-On Research:  Data Science and Machine Learning Applications for Images and Behavior Analysis

### Models and Methods for Image and Text data with ML.

Why will it be interesting to have you enroll in this summer camp? Would you like to increase your knowledge and creativity using science, technology, mathematics, and you want to know the models used by the most prominent companies to track your interests. In this Hands-On Research for Undergraduates program, we will deliver the main concepts that combine statistical and computational theory to create and train AI (Machine Learning) models for classification and prediction problems in the field of image and Behavior analysis. Hands-On Research will take place on ------------- (8 weeks).    

The summer camp will provide experience in **formulating** and carrying out a tangible **data science analysis** with real-world data. The capstone will be a **group/team project (3/5 students)** and each project will focus in open, pre-existing secondary data.  

Students will be computing with data using popular language like *Python and R*, but also specific languages for transforming and manipulating text, and for managing complex computational pipelines.  

One of the outcomes of the summer project will be to develop a **package that abstract commonly used pieces of workflow** and make them available for use in **future projects**. 

The student will learn how to analyze and interpret geospatial images to classify the diverse types of vegetation presented in the image.


